### ISSUE TITLE
max recursion reached

### ISSUE THREAD

**Issue by wideglide** [ossf/fuzz-introspector#23]
I tried this with libxml2 and ran into an error during post-processing:

```
INFO:__main__:Running fuzz introspector post-processing
INFO:__main__:[+] Loading profiles
INFO:fuzz_data_loader: - found 8 profiles to load
INFO:fuzz_data_loader: - loading /src/inspector-tmp/fuzzerLogFile-2.data
INFO:fuzz_data_loader: - loading /src/inspector-tmp/fuzzerLogFile-3.data
INFO:fuzz_data_loader: - loading /src/inspector-tmp/fuzzerLogFile-0.data
INFO:fuzz_data_loader: - loading /src/inspector-tmp/uri.data
INFO:fuzz_data_loader: - loading /src/inspector-tmp/fuzzerLogFile-4.data
INFO:fuzz_data_loader: - loading /src/inspector-tmp/fuzzerLogFile-5.data
INFO:fuzz_data_loader: - loading /src/inspector-tmp/fuzzerLogFile-1.data
INFO:fuzz_data_loader: - loading /src/inspector-tmp/global.data
INFO:__main__:[+] Accummulating profiles
INFO:__main__:[+] Creating project profile
INFO:__main__:[+] Refining profiles
INFO:__main__:[+] Creating HTML report
INFO:fuzz_html: - Creating top section
INFO:fuzz_html: - Identifying optimal targets
INFO:fuzz_analysis:  - in analysis_synthesize_simple_targets
Traceback (most recent call last):
  File "/src/post-processing/main.py", line 83, in <module>
    run_analysis_on_dir(args.target_dir, args.git_repo_url, args.coverage_url)
  File "/src/post-processing/main.py", line 53, in run_analysis_on_dir
    fuzz_html.create_html_report(profiles, project_profile, coverage_url, git_repo_url, basefolder)
  File "/src/post-processing/fuzz_html.py", line 559, in create_html_report
    fuzz_targets_2, new_profile_2, opt_2 = fuzz_analysis.analysis_synthesize_simple_targets(
  File "/src/post-processing/fuzz_analysis.py", line 93, in analysis_synthesize_simple_targets
    new_merged_profile = copy.deepcopy(merged_profile)
  File "/usr/local/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)

<snip>

  File "/usr/local/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/local/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/local/lib/python3.8/copy.py", line 202, in _deepcopy_list
    memo[id(x)] = y
RecursionError: maximum recursion depth exceeded while calling a Python object
ERROR:root:Building fuzzers failed.
```

**Comment by DavidKorczynski** [comment]
Thanks a lot! just to confirm - you're building this by way of OSS-Fuzz, right?

**Comment by wideglide** [comment]
Yes - I followed the oss_fuzz_integration/README.md just substituting libxml2 for htslib.

**Comment by wideglide** [comment]
this seems to be fixed now, thanks!

**Comment by DavidKorczynski** [comment]
Wonderful - I pushed some things that would remove recursion and also speed up the code in general. Can confirm that libxml2 works on my machine as well.

Thanks for reporting the issue.
