### ISSUE TITLE
Issue when splitting branch_string

### ISSUE THREAD

**Issue by DavidKorczynski** [ossf/fuzz-introspector#285]
Running `run_both.sh tarantool 30` I get:

```
Traceback (most recent call last):
  File "/fuzz-introspector/post-processing/main.py", line 191, in <module>
    main()
  File "/fuzz-introspector/post-processing/main.py", line 177, in main
    return_code = run_analysis_on_dir(
  File "/fuzz-introspector/post-processing/main.py", line 91, in run_analysis_on_dir
    fuzz_analysis.overlay_calltree_with_coverage(
  File "/fuzz-introspector/post-processing/fuzz_analysis.py", line 255, in overlay_calltree_with_coverage
    branch_blockers = detect_branch_level_blockers(profile)
  File "/fuzz-introspector/post-processing/fuzz_analysis.py", line 342, in detect_branch_level_blockers
    function_name, rest_string = branch_string.split(':')
ValueError: too many values to unpack (expected 2)
```

**Comment by DavidKorczynski** [comment]
This has been fixed with a try-except. Am not sure if another solution is desired in the long run

**Comment by Navidem** [comment]
This is fixed.
