### ISSUE TITLE
Issue when loading wuffs branch data

### ISSUE THREAD

**Issue by DavidKorczynski** [ossf/fuzz-introspector#288]
When running the `run_both.sh wuffs 30` I get the following exception:
```
INFO:fuzz_analysis:Using coverage url: /covreport/tga_fuzzer/linux
Traceback (most recent call last):
  File "/fuzz-introspector/post-processing/main.py", line 192, in <module>
    main()
  File "/fuzz-introspector/post-processing/main.py", line 177, in main
    return_code = run_analysis_on_dir(
  File "/fuzz-introspector/post-processing/main.py", line 91, in run_analysis_on_dir
    fuzz_analysis.overlay_calltree_with_coverage(
  File "/fuzz-introspector/post-processing/fuzz_analysis.py", line 255, in overlay_calltree_with_coverage
    branch_blockers = detect_branch_level_blockers(profile)
  File "/fuzz-introspector/post-processing/fuzz_analysis.py", line 350, in detect_branch_level_blockers
    llvm_branch_profile = functions_profile[function_name].branch_profiles
KeyError: 'wuffs_bzip2__decoder__initialize'

```

**Comment by DavidKorczynski** [comment]
Pushed a fix as this issue was blocking another issue -- but the fix should maybe change in the long run as I simply set it to skip if the function name was not in the dictionary

**Comment by Navidem** [comment]
This is fixed.
