### ISSUE TITLE
Projects failing

### ISSUE THREAD

**Issue by DavidKorczynski** [ossf/fuzz-introspector#30]
Please add projects that fail compilation in here

- bitcoin-core
- nss

**Comment by DavidKorczynski** [comment]
@Navidem I just tried nss and it killed my machine - most likely due to some resource exhaustion but am yet to isolate whether it's due to LTO or fuzz-introspector, or something third

**Comment by Navidem** [comment]
@DavidKorczynski thanks for checking. I can say without LTO it finishes successfully within ~7 min on my side.

**Comment by DavidKorczynski** [comment]
> @DavidKorczynski thanks for checking. I can say without LTO it finishes successfully within ~7 min on my side.

I too compile it fine with `python3 infra/helper.py build_fuzzers nss`

**Comment by DavidKorczynski** [comment]
I can now build NSS with fuzz-introspector: 

The issue is that NSS uses a lot of processes during compilation and each of these also uses a lot of memory.  This can be solved by changing this line `https://hg.mozilla.org/projects/nss/file/tip/build.sh#l276` form `run_scanbuild "$ninja" -C "$target_dir" "${ninja_params[@]}"` to `run_scanbuild "$ninja" -C "$target_dir" -j 2 "${ninja_params[@]}"`

I will explore if we can use some constraints on the Docker environment, e.g. https://docs.docker.com/config/containers/resource_constraints/#cpu This should work in a general way.

**Comment by oliverchang** [comment]
@Navidem Let's create sub bugs and track them here for the ones you notice too!

**Comment by Navidem** [comment]
`freeimage` fails to compile. Apparently it is not compatible with -flto.

**Comment by Navidem** [comment]
Division by zero in `post-processing/main.py`
These projects encounter div by zero once the profile is not produced or fail to merge:
- croaring
- nettle
- abseil-cpp

Sample output for `abseil-cpp`:
```
Step #6 - "compile-libfuzzer-introspector-x86_64": INFO:__main__:[+] Loading profiles
Step #6 - "compile-libfuzzer-introspector-x86_64": INFO:fuzz_data_loader: - found 0 profiles to load
Step #6 - "compile-libfuzzer-introspector-x86_64": INFO:__main__:[+] Accummulating profiles
Step #6 - "compile-libfuzzer-introspector-x86_64": INFO:__main__:[+] Creating project profile
Step #6 - "compile-libfuzzer-introspector-x86_64": INFO:fuzz_data_loader:Creating merged profile of 0 profiles
Step #6 - "compile-libfuzzer-introspector-x86_64": INFO:fuzz_data_loader:Populating functions reached
Step #6 - "compile-libfuzzer-introspector-x86_64": INFO:fuzz_data_loader:Populating functions unreached
Step #6 - "compile-libfuzzer-introspector-x86_64": INFO:fuzz_data_loader:Creating all_functions dictionary
Step #6 - "compile-libfuzzer-introspector-x86_64": INFO:fuzz_data_loader:Gathering complexity and incoming references of each function
Step #6 - "compile-libfuzzer-introspector-x86_64": INFO:fuzz_data_loader:Completed creationg of merged profile
Step #6 - "compile-libfuzzer-introspector-x86_64": INFO:__main__:[+] Refining profiles
Step #6 - "compile-libfuzzer-introspector-x86_64": INFO:__main__:[+] Creating HTML report
Step #6 - "compile-libfuzzer-introspector-x86_64": INFO:fuzz_html: - Creating HTML report
Step #6 - "compile-libfuzzer-introspector-x86_64": INFO:fuzz_html: - Creating reachability overview table
Step #6 - "compile-libfuzzer-introspector-x86_64": Traceback (most recent call last):
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/post-processing/main.py", line 73, in <module>
Step #6 - "compile-libfuzzer-introspector-x86_64":     run_analysis_on_dir(args.target_dir, args.git_repo_url, args.coverage_url)
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/post-processing/main.py", line 44, in run_analysis_on_dir
Step #6 - "compile-libfuzzer-introspector-x86_64":     fuzz_html.create_html_report(
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/post-processing/fuzz_html.py", line 526, in create_html_report
Step #6 - "compile-libfuzzer-introspector-x86_64":     html_string += create_top_summary_info(tables, project_profile)
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/post-processing/fuzz_html.py", line 261, in create_top_summary_info
Step #6 - "compile-libfuzzer-introspector-x86_64":     functions_percentage = ((len(total_reached_functions)*1.0) / (len(total_reached_functions) + len(
Step #6 - "compile-libfuzzer-introspector-x86_64": ZeroDivisionError: float division by zero
```

Sample output for `nettle`:
```
Step #6 - "compile-libfuzzer-introspector-x86_64": INFO:__main__:[+] Loading profiles
Step #6 - "compile-libfuzzer-introspector-x86_64": INFO:fuzz_utils:f: fuzzerLogFile-1.data -- matches regex: fuzzerLogFile.*\.data$
Step #6 - "compile-libfuzzer-introspector-x86_64": INFO:fuzz_utils:f: fuzzerLogFile-0.data -- matches regex: fuzzerLogFile.*\.data$
Step #6 - "compile-libfuzzer-introspector-x86_64": INFO:fuzz_data_loader: - found 2 profiles to load
Step #6 - "compile-libfuzzer-introspector-x86_64": INFO:fuzz_data_loader: - loading /src/inspector/fuzzerLogFile-1.data
Step #6 - "compile-libfuzzer-introspector-x86_64": INFO:fuzz_data_loader: - loading /src/inspector/fuzzerLogFile-0.data
Step #6 - "compile-libfuzzer-introspector-x86_64": INFO:__main__:[+] Accummulating profiles
Step #6 - "compile-libfuzzer-introspector-x86_64": INFO:__main__:[+] Creating project profile
Step #6 - "compile-libfuzzer-introspector-x86_64": INFO:fuzz_data_loader:Creating merged profile of 0 profiles
Step #6 - "compile-libfuzzer-introspector-x86_64": INFO:fuzz_data_loader:Populating functions reached
Step #6 - "compile-libfuzzer-introspector-x86_64": INFO:fuzz_data_loader:Populating functions unreached
Step #6 - "compile-libfuzzer-introspector-x86_64": INFO:fuzz_data_loader:Creating all_functions dictionary
Step #6 - "compile-libfuzzer-introspector-x86_64": INFO:fuzz_data_loader:Gathering complexity and incoming references of each function
Step #6 - "compile-libfuzzer-introspector-x86_64": INFO:fuzz_data_loader:Completed creationg of merged profile
Step #6 - "compile-libfuzzer-introspector-x86_64": INFO:__main__:[+] Refining profiles
Step #6 - "compile-libfuzzer-introspector-x86_64": INFO:__main__:[+] Creating HTML report
Step #6 - "compile-libfuzzer-introspector-x86_64": INFO:fuzz_html: - Creating HTML report
Step #6 - "compile-libfuzzer-introspector-x86_64": INFO:fuzz_html: - Creating reachability overview table
Step #6 - "compile-libfuzzer-introspector-x86_64": Traceback (most recent call last):
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/post-processing/main.py", line 73, in <module>
Step #6 - "compile-libfuzzer-introspector-x86_64":     run_analysis_on_dir(args.target_dir, args.git_repo_url, args.coverage_url)
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/post-processing/main.py", line 44, in run_analysis_on_dir
Step #6 - "compile-libfuzzer-introspector-x86_64":     fuzz_html.create_html_report(
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/post-processing/fuzz_html.py", line 526, in create_html_report
Step #6 - "compile-libfuzzer-introspector-x86_64":     html_string += create_top_summary_info(tables, project_profile)
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/post-processing/fuzz_html.py", line 261, in create_top_summary_info
Step #6 - "compile-libfuzzer-introspector-x86_64":     functions_percentage = ((len(total_reached_functions)*1.0) / (len(total_reached_functions) + len(
Step #6 - "compile-libfuzzer-introspector-x86_64": ZeroDivisionError: float division by zero
```

**Comment by Navidem** [comment]
The following projects fail to parse/merge profile because of encoding issues:
- kamailio

Sample output for 'kamailio':
```
Step #6 - "compile-libfuzzer-introspector-x86_64": INFO:__main__:[+] Loading profiles
Step #6 - "compile-libfuzzer-introspector-x86_64": INFO:fuzz_utils:f: fuzzerLogFile-1.data -- matches regex: fuzzerLogFile.*\.data$
Step #6 - "compile-libfuzzer-introspector-x86_64": INFO:fuzz_utils:f: fuzzerLogFile-0.data -- matches regex: fuzzerLogFile.*\.data$
Step #6 - "compile-libfuzzer-introspector-x86_64": INFO:fuzz_data_loader: - found 2 profiles to load
Step #6 - "compile-libfuzzer-introspector-x86_64": INFO:fuzz_data_loader: - loading /src/inspector/fuzzerLogFile-1.data
Step #6 - "compile-libfuzzer-introspector-x86_64": INFO:fuzz_data_loader: - loading /src/inspector/fuzzerLogFile-0.data
Step #6 - "compile-libfuzzer-introspector-x86_64": INFO:__main__:[+] Accummulating profiles
Step #6 - "compile-libfuzzer-introspector-x86_64": INFO:fuzz_utils:f: fuzz_parse_msg.covreport -- matches regex: .*\.covreport$
Step #6 - "compile-libfuzzer-introspector-x86_64": INFO:fuzz_utils:f: fuzz_uri.covreport -- matches regex: .*\.covreport$
Step #6 - "compile-libfuzzer-introspector-x86_64": Traceback (most recent call last):
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/post-processing/main.py", line 73, in <module>
Step #6 - "compile-libfuzzer-introspector-x86_64":     run_analysis_on_dir(args.target_dir, args.git_repo_url, args.coverage_url)
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/post-processing/main.py", line 34, in run_analysis_on_dir
Step #6 - "compile-libfuzzer-introspector-x86_64":     profile.accummulate_profile(target_folder)
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/post-processing/fuzz_data_loader.py", line 196, in accummulate_profile
Step #6 - "compile-libfuzzer-introspector-x86_64":     self.load_coverage(target_folder)
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/post-processing/fuzz_data_loader.py", line 125, in load_coverage
Step #6 - "compile-libfuzzer-introspector-x86_64":     functions_hit, coverage_map = fuzz_cov_load.llvm_cov_load(target_folder, self.get_target_fuzzer_filename())
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/post-processing/fuzz_cov_load.py", line 50, in llvm_cov_load
Step #6 - "compile-libfuzzer-introspector-x86_64":     for line in pf:
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/usr/local/lib/python3.8/codecs.py", line 322, in decode
Step #6 - "compile-libfuzzer-introspector-x86_64":     (result, consumed) = self._buffer_decode(data, self.errors, final)
Step #6 - "compile-libfuzzer-introspector-x86_64": UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 3854: invalid start byte
```

**Comment by DavidKorczynski** [comment]
> Division by zero in `post-processing/main.py`
> These projects encounter div by zero once the profile is not produced or fail to merge:

FIxed in https://github.com/ossf/fuzz-introspector/commit/b03c4cfcfbec51779133adf24d14d78425e9121c

**Comment by DavidKorczynski** [comment]
> 

Kamailio should be fixed with https://github.com/ossf/fuzz-introspector/commit/554ae742c4d576da2b6334e132cda1ad6e016316 

have run locally where I verified the issue and also verified post-fix that it works now

**Comment by DavidKorczynski** [comment]
> Division by zero in `post-processing/main.py` These projects encounter div by zero once the profile is not produced or fail to merge:
> 
> * croaring
> * nettle
> * abseil-cpp
> 

This issue seem to have happened because these lines in the OSS-Fuzz integration:

https://github.com/google/oss-fuzz/blob/cb45dab05cdd76d34e2f16cdd96a1c1c1d12d701/infra/base-images/base-builder/compile#L210-L211

The problem is those `find` commands can overwrite fuzzer profiles if the fuzzer profiles have the same name. Fuzzer profiles will often have the same filename but in different locations. 

I fixed this by adding a UUID to the fuzzer log files now: https://github.com/ossf/fuzz-introspector/commit/4231c270ce6d8750b1b774f1f2ddca74f5c40d22 and I have verified that both croaring and nettle works now. As such, it shouldn't really happen now, but, the two lines I link to in the OSS-Fuzz integration should probably change considering fuzz introspector does not guarantee uniqueness (it *almost* does not) in output files.

**Comment by Navidem** [comment]
The following projects are failing with configure error `Unknown float word ordering.`

- mercurial
- python3-libraries
- cpython3

A quick search shows people [recommending](https://bugs.gentoo.org/700012#c11) use of `-ffat-lto-objects` when compiling for lto. Have not yet tested.

**Comment by DavidKorczynski** [comment]
I added a small script to automate testing projects of oss-fuzz projects here https://github.com/ossf/fuzz-introspector/blob/main/oss_fuzz_integration/test_projects.sh

**Comment by DavidKorczynski** [comment]
`quickjs` is working for me

**Comment by DavidKorczynski** [comment]
`wuffs` is working for me, although the reports have fairly limited calltrees, and I think this is because of use of indirect pointers, e.g.: https://github.com/google/wuffs/blob/ccbec1833094b1d2ee18b969aaae356a46bc5b30/internal/cgen/base/pixconv-submodule.c#L5270-L5281

Ref https://github.com/ossf/fuzz-introspector/issues/4

**Comment by DavidKorczynski** [comment]
Are we sure that all of these projects are related to fuzz-introspector? I am asking this because I debugged an issue over here https://github.com/ossf/fuzz-introspector/issues/48#issuecomment-1063163173 where it seems that the issue only happens when compiling with `--sanitizer=introspector`, however, the issue occurs even if `FUZZ_INTROSPECTOR` is unset, meaning that fuzz-introspector is essentially not run.

One of the potential issues is that `--sanitizer=introspector` also applies some other changes, such as specify ```
export LDFLAGS="-fuse-ld=gold"
export AR=llvm-ar
export RANLIB=llvm-ranlib
```

I recon it would be nice to have some infrastructure to make it easy to isolate whether a given issue happens because of the fuzz-introspector llvm pass or e.g. the fact that we force use of `-fuse-ld=gold`. Also, it may seem that some issues only happens in the OSS-Fuzz environment, e.g. `jsoncpp`. 

I am currently looking at `curl` where I am suspecting the issue doesn't happen because of fuzz-introspector code but rather switchig to a linker that is not supported by curl. This infrastructure might be included herehttps://github.com/ossf/fuzz-introspector/issues/41

**Comment by Navidem** [comment]
cleared v1 milestone, as the debugging remaining failures has to continue afterwards.
