### ISSUE TITLE
in create_horisontal_calltree_image     multiplier = plot_size / len(color_list) ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by MarcoFalke** [ossf/fuzz-introspector#32]
Steps to reproduce (needs cryptofuzz disabled for bitcoin-core):

```
podman system reset && ./build_patched_oss_fuzz.sh && cd oss-fuzz && time ../run_both.sh bitcoin-core 1
```

```
INFO:__main__:[+] Creating project profile
INFO:fuzz_data_loader:Creating merged profile of 2 profiles
INFO:fuzz_data_loader:Populating functions reached
INFO:fuzz_data_loader:Populating functions unreached
INFO:fuzz_data_loader:Creating all_functions dictionary
INFO:fuzz_data_loader:Gathering complexity and incoming references of each function
INFO:fuzz_data_loader:Completed creationg of merged profile
INFO:__main__:[+] Refining profiles
INFO:__main__:[+] Creating HTML report
INFO:fuzz_html: - Creating HTML report
INFO:fuzz_html: - Creating reachability overview table
INFO:fuzz_html: - Creating table with overview of all fuzzers
INFO:fuzz_html: - Creating table with information about all functions in target
INFO:fuzz_html: - Creating section with details about each fuzzer
INFO:fuzz_html:Creating image srcbitcoin-coresrctestfuzzfuzz.cpp_colormap.png
INFO:fuzz_html:Creating image srcbitcoin-coreconftest.cpp_colormap.png
Traceback (most recent call last):
  File "/src/post-processing/main.py", line 73, in <module>
    run_analysis_on_dir(args.target_dir, args.git_repo_url, args.coverage_url)
  File "/src/post-processing/main.py", line 44, in run_analysis_on_dir
    fuzz_html.create_html_report(
  File "/src/post-processing/fuzz_html.py", line 548, in create_html_report
    html_string += create_fuzzer_detailed_section(profiles[profile_idx], toc_list, tables, profile_idx, project_profile, coverage_url, git_repo_url, basefolder)
  File "/src/post-processing/fuzz_html.py", line 389, in create_fuzzer_detailed_section
    html_string += create_calltree(profile, project_profile, coverage_url, git_repo_url, basefolder, image_name, tables)
  File "/src/post-processing/fuzz_html.py", line 347, in create_calltree
    create_horisontal_calltree_image(image_name, color_sequence)
  File "/src/post-processing/fuzz_html.py", line 50, in create_horisontal_calltree_image
    multiplier = plot_size / len(color_list)
ZeroDivisionError: float division by zero
ERROR:root:Building fuzzers failed.

real	322m3.244s
user	8m0.454s
sys	6m29.575s

**Comment by DavidKorczynski** [comment]
> Steps to reproduce (needs clusterfuzz disabled for bitcoin-core):
> 

Just to clarify, you mean cryptofuzz right? and the only diff required is this:

```
oss-fuzz/projects/bitcoin-core$ git diff ./
diff --git a/projects/bitcoin-core/build.sh b/projects/bitcoin-core/build.sh
index 5c6ac475..eb3a3470 100755
--- a/projects/bitcoin-core/build.sh
+++ b/projects/bitcoin-core/build.sh
@@ -15,7 +15,7 @@
 #
 ################################################################################
 
-$SRC/build_cryptofuzz.sh
+#$SRC/build_cryptofuzz.sh

```
?

**Comment by MarcoFalke** [comment]
Ooops early-morning typo.

Your diff is correct.

**Comment by MarcoFalke** [comment]
Fixed, thanks
