### ISSUE TITLE
FI seems to be failing with "KeyError: 'Callsites'"

### ISSUE THREAD

**Issue by evverx** [ossf/fuzz-introspector#476]
```sh
../run_both.sh dbus-broker 60
...
Traceback (most recent call last):
  File "/fuzz-introspector/src/main.py", line 141, in <module>
    main()
  File "/fuzz-introspector/src/main.py", line 122, in main
    return_code = commands.run_analysis_on_dir(
  File "/fuzz-introspector/src/fuzz_introspector/commands.py", line 53, in run_analysis_on_dir
    profiles = data_loader.load_all_profiles(target_folder, language)
  File "/fuzz-introspector/src/fuzz_introspector/data_loader.py", line 152, in load_all_profiles
    profile = read_fuzzer_data_file_to_profile(data_file, language)
  File "/fuzz-introspector/src/fuzz_introspector/data_loader.py", line 61, in read_fuzzer_data_file_to_profile
    FP = fuzzer_profile.FuzzerProfile(cfg_file, data_dict_yaml, language)
  File "/fuzz-introspector/src/fuzz_introspector/datatypes/fuzzer_profile.py", line 69, in __init__
    self._set_function_list(frontend_yaml)
  File "/fuzz-introspector/src/fuzz_introspector/datatypes/fuzzer_profile.py", line 405, in _set_function_list
    func_profile = function_profile.FunctionProfile(elem)
  File "/fuzz-introspector/src/fuzz_introspector/datatypes/function_profile.py", line 55, in __init__
    self.callsite = self.load_func_callsites(elem['Callsites'])
KeyError: 'Callsites'
The following command is about to be run to start a webserver: cd ./corpus-0/inspector-report/ && python3 -m http.server 8008
```
What's weird is that even though FI failed its exit code was 0 apparently and the script proceeded to launch a web server.

**Comment by DavidKorczynski** [comment]
Thanks! This is a nasty regression, I'll fix it up shortly.
