### ISSUE TITLE
PyCG runtime crash

### ISSUE THREAD

**Issue by Navidem** [ossf/fuzz-introspector#679]
I noticed some python projects are failing with the following runtime crash:
project: `g-py-bigquery`, [Full log](https://oss-fuzz-build-logs.storage.googleapis.com/log-daa6d8b3-b5dd-4504-980f-813ae83ee56c.txt).

I recommend a complete check for python projects build statuses.

```
Step #6 - "compile-libfuzzer-introspector-x86_64": Traceback (most recent call last):
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/frontends/python/main.py", line 369, in <module>
Step #6 - "compile-libfuzzer-introspector-x86_64":     sys.exit(main())
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/frontends/python/main.py", line 357, in main
Step #6 - "compile-libfuzzer-introspector-x86_64":     exit_code = run_fuzz_pass(
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/frontends/python/main.py", line 112, in run_fuzz_pass
Step #6 - "compile-libfuzzer-introspector-x86_64":     cg.analyze()
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/frontends/python/PyCG/pycg/pycg.py", line 191, in analyze
Step #6 - "compile-libfuzzer-introspector-x86_64":     self.do_pass(PostProcessor, False,
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/frontends/python/PyCG/pycg/pycg.py", line 159, in do_pass
Step #6 - "compile-libfuzzer-introspector-x86_64":     processor.analyze()
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/frontends/python/PyCG/pycg/processing/postprocessor.py", line 388, in analyze
Step #6 - "compile-libfuzzer-introspector-x86_64":     self.analyze_submodules()
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/frontends/python/PyCG/pycg/processing/postprocessor.py", line 375, in analyze_submodules
Step #6 - "compile-libfuzzer-introspector-x86_64":     super().analyze_submodules(PostProcessor, self.import_manager,
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/frontends/python/PyCG/pycg/processing/base.py", line 612, in analyze_submodules
Step #6 - "compile-libfuzzer-introspector-x86_64":     self.analyze_submodule(cls, imp, *args, **kwargs)
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/frontends/python/PyCG/pycg/processing/base.py", line 630, in analyze_submodule
Step #6 - "compile-libfuzzer-introspector-x86_64":     visitor.analyze()
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/frontends/python/PyCG/pycg/processing/postprocessor.py", line 388, in analyze
Step #6 - "compile-libfuzzer-introspector-x86_64":     self.analyze_submodules()
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/frontends/python/PyCG/pycg/processing/postprocessor.py", line 375, in analyze_submodules
Step #6 - "compile-libfuzzer-introspector-x86_64":     super().analyze_submodules(PostProcessor, self.import_manager,
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/frontends/python/PyCG/pycg/processing/base.py", line 612, in analyze_submodules
Step #6 - "compile-libfuzzer-introspector-x86_64":     self.analyze_submodule(cls, imp, *args, **kwargs)
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/frontends/python/PyCG/pycg/processing/base.py", line 630, in analyze_submodule
Step #6 - "compile-libfuzzer-introspector-x86_64":     visitor.analyze()
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/frontends/python/PyCG/pycg/processing/postprocessor.py", line 388, in analyze
Step #6 - "compile-libfuzzer-introspector-x86_64":     self.analyze_submodules()
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/frontends/python/PyCG/pycg/processing/postprocessor.py", line 375, in analyze_submodules
Step #6 - "compile-libfuzzer-introspector-x86_64":     super().analyze_submodules(PostProcessor, self.import_manager,
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/frontends/python/PyCG/pycg/processing/base.py", line 612, in analyze_submodules
Step #6 - "compile-libfuzzer-introspector-x86_64":     self.analyze_submodule(cls, imp, *args, **kwargs)
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/frontends/python/PyCG/pycg/processing/base.py", line 630, in analyze_submodule
Step #6 - "compile-libfuzzer-introspector-x86_64":     visitor.analyze()
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/frontends/python/PyCG/pycg/processing/postprocessor.py", line 388, in analyze
Step #6 - "compile-libfuzzer-introspector-x86_64":     self.analyze_submodules()
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/frontends/python/PyCG/pycg/processing/postprocessor.py", line 375, in analyze_submodules
Step #6 - "compile-libfuzzer-introspector-x86_64":     super().analyze_submodules(PostProcessor, self.import_manager,
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/frontends/python/PyCG/pycg/processing/base.py", line 612, in analyze_submodules
Step #6 - "compile-libfuzzer-introspector-x86_64":     self.analyze_submodule(cls, imp, *args, **kwargs)
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/frontends/python/PyCG/pycg/processing/base.py", line 630, in analyze_submodule
Step #6 - "compile-libfuzzer-introspector-x86_64":     visitor.analyze()
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/frontends/python/PyCG/pycg/processing/postprocessor.py", line 388, in analyze
Step #6 - "compile-libfuzzer-introspector-x86_64":     self.analyze_submodules()
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/frontends/python/PyCG/pycg/processing/postprocessor.py", line 375, in analyze_submodules
Step #6 - "compile-libfuzzer-introspector-x86_64":     super().analyze_submodules(PostProcessor, self.import_manager,
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/frontends/python/PyCG/pycg/processing/base.py", line 612, in analyze_submodules
Step #6 - "compile-libfuzzer-introspector-x86_64":     self.analyze_submodule(cls, imp, *args, **kwargs)
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/frontends/python/PyCG/pycg/processing/base.py", line 630, in analyze_submodule
Step #6 - "compile-libfuzzer-introspector-x86_64":     visitor.analyze()
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/frontends/python/PyCG/pycg/processing/postprocessor.py", line 388, in analyze
Step #6 - "compile-libfuzzer-introspector-x86_64":     self.analyze_submodules()
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/frontends/python/PyCG/pycg/processing/postprocessor.py", line 375, in analyze_submodules
Step #6 - "compile-libfuzzer-introspector-x86_64":     super().analyze_submodules(PostProcessor, self.import_manager,
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/frontends/python/PyCG/pycg/processing/base.py", line 612, in analyze_submodules
Step #6 - "compile-libfuzzer-introspector-x86_64":     self.analyze_submodule(cls, imp, *args, **kwargs)
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/frontends/python/PyCG/pycg/processing/base.py", line 630, in analyze_submodule
Step #6 - "compile-libfuzzer-introspector-x86_64":     visitor.analyze()
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/frontends/python/PyCG/pycg/processing/postprocessor.py", line 388, in analyze
Step #6 - "compile-libfuzzer-introspector-x86_64":     self.analyze_submodules()
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/frontends/python/PyCG/pycg/processing/postprocessor.py", line 375, in analyze_submodules
Step #6 - "compile-libfuzzer-introspector-x86_64":     super().analyze_submodules(PostProcessor, self.import_manager,
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/frontends/python/PyCG/pycg/processing/base.py", line 612, in analyze_submodules
Step #6 - "compile-libfuzzer-introspector-x86_64":     self.analyze_submodule(cls, imp, *args, **kwargs)
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/frontends/python/PyCG/pycg/processing/base.py", line 630, in analyze_submodule
Step #6 - "compile-libfuzzer-introspector-x86_64":     visitor.analyze()
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/frontends/python/PyCG/pycg/processing/postprocessor.py", line 388, in analyze
Step #6 - "compile-libfuzzer-introspector-x86_64":     self.analyze_submodules()
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/frontends/python/PyCG/pycg/processing/postprocessor.py", line 375, in analyze_submodules
Step #6 - "compile-libfuzzer-introspector-x86_64":     super().analyze_submodules(PostProcessor, self.import_manager,
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/frontends/python/PyCG/pycg/processing/base.py", line 612, in analyze_submodules
Step #6 - "compile-libfuzzer-introspector-x86_64":     self.analyze_submodule(cls, imp, *args, **kwargs)
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/frontends/python/PyCG/pycg/processing/base.py", line 630, in analyze_submodule
Step #6 - "compile-libfuzzer-introspector-x86_64":     visitor.analyze()
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/frontends/python/PyCG/pycg/processing/postprocessor.py", line 388, in analyze
Step #6 - "compile-libfuzzer-introspector-x86_64":     self.analyze_submodules()
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/frontends/python/PyCG/pycg/processing/postprocessor.py", line 375, in analyze_submodules
Step #6 - "compile-libfuzzer-introspector-x86_64":     super().analyze_submodules(PostProcessor, self.import_manager,
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/frontends/python/PyCG/pycg/processing/base.py", line 612, in analyze_submodules
Step #6 - "compile-libfuzzer-introspector-x86_64":     self.analyze_submodule(cls, imp, *args, **kwargs)
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/frontends/python/PyCG/pycg/processing/base.py", line 630, in analyze_submodule
Step #6 - "compile-libfuzzer-introspector-x86_64":     visitor.analyze()
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/frontends/python/PyCG/pycg/processing/postprocessor.py", line 388, in analyze
Step #6 - "compile-libfuzzer-introspector-x86_64":     self.analyze_submodules()
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/frontends/python/PyCG/pycg/processing/postprocessor.py", line 375, in analyze_submodules
Step #6 - "compile-libfuzzer-introspector-x86_64":     super().analyze_submodules(PostProcessor, self.import_manager,
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/frontends/python/PyCG/pycg/processing/base.py", line 612, in analyze_submodules
Step #6 - "compile-libfuzzer-introspector-x86_64":     self.analyze_submodule(cls, imp, *args, **kwargs)
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/frontends/python/PyCG/pycg/processing/base.py", line 630, in analyze_submodule
Step #6 - "compile-libfuzzer-introspector-x86_64":     visitor.analyze()
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/frontends/python/PyCG/pycg/processing/postprocessor.py", line 383, in analyze
Step #6 - "compile-libfuzzer-introspector-x86_64":     self.visit(ast.parse(self.contents, self.filename))
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/usr/lib/python3.9/ast.py", line 407, in visit
Step #6 - "compile-libfuzzer-introspector-x86_64":     return visitor(node)
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/frontends/python/PyCG/pycg/processing/base.py", line 88, in visit_Module
Step #6 - "compile-libfuzzer-introspector-x86_64":     self.generic_visit(node)
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/usr/lib/python3.9/ast.py", line 415, in generic_visit
Step #6 - "compile-libfuzzer-introspector-x86_64":     self.visit(item)
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/usr/lib/python3.9/ast.py", line 407, in visit
Step #6 - "compile-libfuzzer-introspector-x86_64":     return visitor(node)
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/frontends/python/PyCG/pycg/processing/postprocessor.py", line 247, in visit_ClassDef
Step #6 - "compile-libfuzzer-introspector-x86_64":     super().visit_ClassDef(node)
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/frontends/python/PyCG/pycg/processing/base.py", line 171, in visit_ClassDef
Step #6 - "compile-libfuzzer-introspector-x86_64":     self.visit(stmt)
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/usr/lib/python3.9/ast.py", line 407, in visit
Step #6 - "compile-libfuzzer-introspector-x86_64":     return visitor(node)
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/frontends/python/PyCG/pycg/processing/postprocessor.py", line 181, in visit_FunctionDef
Step #6 - "compile-libfuzzer-introspector-x86_64":     arg_def.get_name_pointer().add(prev_name)
Step #6 - "compile-libfuzzer-introspector-x86_64": AttributeError: 'NoneType' object has no attribute 'get_name_pointer'
```

**Comment by DavidKorczynski** [comment]
Fix on the pycg side: https://github.com/AdaLogics/PyCG/commit/67e4be8c1c69340e0c2c6944d7a309e336188f8e
