### ISSUE TITLE
issue running htslib

### ISSUE THREAD

**Issue by DavidKorczynski** [ossf/fuzz-introspector#698]
Am getting the following from a run of `htslib`
```
INFO:fuzz_introspector.data_loader: - loading /src/inspector/fuzzerLogFile-0-kS5a3lgLhf.data

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/fuzz-introspector/src/fuzz_introspector/data_loader.py", line 143, in _load_profile
    profile = read_fuzzer_data_file_to_profile(data_file, language)
  File "/fuzz-introspector/src/fuzz_introspector/data_loader.py", line 62, in read_fuzzer_data_file_to_profile
    profile = fuzzer_profile.FuzzerProfile(cfg_file, data_dict_yaml, language)
  File "/fuzz-introspector/src/fuzz_introspector/datatypes/fuzzer_profile.py", line 73, in __init__
    self._set_function_list(frontend_yaml)
  File "/fuzz-introspector/src/fuzz_introspector/datatypes/fuzzer_profile.py", line 500, in _set_function_list
    func_profile = function_profile.FunctionProfile(elem)
  File "/fuzz-introspector/src/fuzz_introspector/datatypes/function_profile.py", line 51, in __init__
    self.branch_profiles = self.load_func_branch_profiles(elem['BranchProfiles'])
  File "/fuzz-introspector/src/fuzz_introspector/datatypes/function_profile.py", line 78, in load_func_branch_profiles
    new_branch.assign_from_yaml_elem(entry)
  File "/fuzz-introspector/src/fuzz_introspector/datatypes/branch_profile.py", line 54, in assign_from_yaml_elem
    bs.pos = br_side_elem['BranchSide']
TypeError: string indices must be integers
INFO:fuzz_introspector.commands:Found no profiles. Exiting
INFO:__main__:Ending fuzz introspector report generation
```

To reproduce:
```
 git clone https://github.com/ossf/fuzz-introspector
 sudo docker system prune -a
 cd fuzz-introspector/
 cd oss_fuzz_integration/
 ./build_post_processing.sh 
 cd oss-fuzz/
 python3 ../runner.py introspector htslib 30 >> log-1.txt 2>&1
```

**Comment by DavidKorczynski** [comment]
I think this is due to fuzz introspector images no longer being produced following https://github.com/google/oss-fuzz/pull/8868 and `build_post_processing.sh` was not updated accordingly: https://github.com/ossf/fuzz-introspector/blob/b3a374fad195a6a1a51d97c3d2bc2fd6387ec8da/oss_fuzz_integration/build_post_processing.sh#L31-L32

Looking here https://console.cloud.google.com/gcr/images/oss-fuzz-base/GLOBAL/base-clang, the last introspector image was ~end October, so it's an old image

**Comment by Navidem** [comment]
> I think this is due to fuzz introspector images no longer being produced following [google/oss-fuzz#8868](https://github.com/google/oss-fuzz/pull/8868) and `build_post_processing.sh` was not updated accordingly:
> 
> https://github.com/ossf/fuzz-introspector/blob/b3a374fad195a6a1a51d97c3d2bc2fd6387ec8da/oss_fuzz_integration/build_post_processing.sh#L31-L32
> 
> Looking here https://console.cloud.google.com/gcr/images/oss-fuzz-base/GLOBAL/base-clang, the last introspector image was ~end October, so it's an old image

Yes, custom images are not the latest anymore. Thanks for updating the builder scripts.
